blank_issues_enabled: false
contact_links:
  - name: Hydrogen Students Community Support
    url: https://github.com/rafaelstz/complete-shopify-hydrogen-course/discussions/categories/q-a
    about: Please ask and answer questions here.